services:
  - type: web
    name: banko-kupon-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    region: frankfurt
    healthCheckPath: /health
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
